Traceback (most recent call last):
  File "snippet.py", line 111, in <module>
    pe2 = pefile.PE(sys.argv[1])
IndexError: list index out of range
